---
abstract: 'Redis Client Terminal'
author:
  - 'Chen Gang <yikuyiku.com@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.9, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Redis-Term
no_index:
  directory:
    - t
    - inc
requires:
  Getopt::Std: 0
  Redis: 1.972
  Term::ReadKey: 2.3
  Term::ReadLine: 1.14
  Term::ReadLine::Perl: 1.0303
  Text::TabularDisplay: 1.35
version: 0.08
